# Car Price Prediction System

## Projenin Amacı

Bu projenin amacı, araç özelliklerine bakarak araba fiyatını tahmin eden bir makine öğrenmesi modeli geliştirmektir.

Model bu bilgileri kullanarak **araç fiyatını tahmin edecektir.**

## Neden Regresyon Problemi?

Bu problem bir **regresyon problemidir** çünkü tahmin edilen değer **sayısal bir değerdir (fiyat)**.

Sınıflandırma problemlerinde sonuç kategori olurken burada sonuç **sürekli bir sayıdır**.

In [41]:
import numpy as np
import pandas as pd

# Rastgele veri üretimi için
np.random.seed(42)

n = 500

year = np.random.randint(2005, 2024, n)
km = np.random.randint(5000, 250000, n)
engine = np.random.uniform(1.0, 3.5, n)
hp = np.random.randint(70, 300, n)

age = 2024 - year

# Fiyat üretimi (sentetik)
price = (
    500000
    + year * 200
    - km * 1.5
    + engine * 80000
    + hp * 1200
    - age * 15000
)

data = pd.DataFrame({
    "year": year,
    "km": km,
    "engine": engine,
    "hp": hp,
    "age": age,
    "price": price
})

data.head()

   year      km    engine   hp  age         price
0  2011  171981  2.864936  244   13  9.712234e+05
1  2019  225411  2.021296  275    5  9.823872e+05
2  2015   24870  3.332345  153    9  1.180883e+06
3  2012  170650  3.477324   91   12  8.538109e+05
4  2011  208196  1.512505  272   13  8.423064e+05

In [42]:
X = data.drop("price", axis=1)
y = data["price"]

In [43]:
X = (X - X.min()) / (X.max() - X.min())

X.head()

       year        km    engine        hp       age
0  0.333333  0.681531  0.746397  0.763158  0.666667
1  0.777778  0.900133  0.408642  0.899123  0.222222
2  0.555556  0.079643  0.933526  0.364035  0.444444
3  0.388889  0.676085  0.991569  0.092105  0.611111
4  0.333333  0.829700  0.204945  0.885965  0.666667

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Train veri sayısı:", len(X_train))
print("Test veri sayısı:", len(X_test))

Train veri sayısı: 400
Test veri sayısı: 100

In [45]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    
    Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
    
    Dense(32, activation="relu"),
    
    Dense(1)   # Output layer (regression)
])

model.summary()

c:\Users\yaren\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 64)             │           384 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,497 (9.75 KB)

 Trainable params: 2,497 (9.75 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.compile(
    optimizer="adam",
    loss="mean_squared_error",
    metrics=["mae"]
)

In [47]:
history = model.fit(

    X_train,
    y_train,

    epochs=50,
    batch_size=32,

    validation_split=0.2
)

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 961810333696.0000 - mae: 966493.6875 - val_loss: 964314005504.0000 - val_mae: 964793.3750
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961809350656.0000 - mae: 966493.1875 - val_loss: 964313088000.0000 - val_mae: 964792.8125
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961808236544.0000 - mae: 966492.6250 - val_loss: 964311580672.0000 - val_mae: 964792.1250
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961806467072.0000 - mae: 966491.6875 - val_loss: 964309483520.0000 - val_mae: 964791.1250
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 961804107776.0000 - mae: 966490.5000 - val_loss: 964306665472.0000 - val_mae: 964789.6250
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 961800699904.0000 - mae: 966488.8125 - val_loss: 964302602240.0000 - val_mae: 964787.5000
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961795981312.0000 - mae: 966486.3750 - val_loss: 964297031680.0000 - val_mae: 964784.6250
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961789689856.0000 - mae: 966483.0000 - val_loss: 964289757184.0000 - val_mae: 964780.8125
Epoch 9/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961781366784.0000 - mae: 966478.6875 - val_loss: 964280254464.0000 - val_mae: 964776.0000
Epoch 10/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961770553344.0000 - mae: 966473.3125 - val_loss: 964268195840.0000 - val_mae: 964769.8125
Epoch 11/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 961757184000.0000 - mae: 966466.3750 - val_loss: 964253188096.0000 - val_mae: 964762.1250
Epoch 12/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961740668928.0000 - mae: 966457.8750 - val_loss: 964234838016.0000 - val_mae: 964752.6250
Epoch 13/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 961720221696.0000 - mae: 966447.3750 - val_loss: 964212686848.0000 - val_mae: 964741.1250
Epoch 14/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961696104448.0000 - mae: 966434.8125 - val_loss: 964186210304.0000 - val_mae: 964727.5000
Epoch 15/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 961667596288.0000 - mae: 966420.1250 - val_loss: 964155277312.0000 - val_mae: 964711.5000
Epoch 16/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961634041856.0000 - mae: 966402.8125 - val_loss: 964119298048.0000 - val_mae: 964692.8750
Epoch 17/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 961595441152.0000 - mae: 966383.0000 - val_loss: 964078206976.0000 - val_mae: 964671.6875
Epoch 18/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 961551400960.0000 - mae: 966360.1875 - val_loss: 964031283200.0000 - val_mae: 964647.5000
Epoch 19/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961501200384.0000 - mae: 966334.6250 - val_loss: 963978461184.0000 - val_mae: 964620.1875
Epoch 20/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 961445429248.0000 - mae: 966305.6250 - val_loss: 963918888960.0000 - val_mae: 964589.5000
Epoch 21/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 961381793792.0000 - mae: 966273.0000 - val_loss: 963853156352.0000 - val_mae: 964555.5000
Epoch 22/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 961312063488.0000 - mae: 966237.0000 - val_loss: 963779624960.0000 - val_mae: 964517.6250
Epoch 23/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961234665472.0000 - mae: 966196.8750 - val_loss: 963698491392.0000 - val_mae: 964475.6875
Epoch 24/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 961149075456.0000 - mae: 966152.8750 - val_loss: 963609362432.0000 - val_mae: 964429.6250
Epoch 25/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 961055883264.0000 - mae: 966104.6875 - val_loss: 963511713792.0000 - val_mae: 964379.3125
Epoch 26/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 960953450496.0000 - mae: 966051.6875 - val_loss: 963405611008.0000 - val_mae: 964324.6250
Epoch 27/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 960842563584.0000 - mae: 965994.3750 - val_loss: 963290464256.0000 - val_mae: 964265.1250
Epoch 28/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 960721977344.0000 - mae: 965932.3750 - val_loss: 963166535680.0000 - val_mae: 964201.0000
Epoch 29/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 960591888384.0000 - mae: 965865.5000 - val_loss: 963032973312.0000 - val_mae: 964132.0000
Epoch 30/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 960453672960.0000 - mae: 965793.6250 - val_loss: 962888138752.0000 - val_mae: 964057.1875
Epoch 31/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 960302678016.0000 - mae: 965715.6875 - val_loss: 962734325760.0000 - val_mae: 963977.6875
Epoch 32/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 960142376960.0000 - mae: 965633.0000 - val_loss: 962569699328.0000 - val_mae: 963892.6875
Epoch 33/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 959971196928.0000 - mae: 965544.8750 - val_loss: 962393931776.0000 - val_mae: 963801.8125
Epoch 34/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 959788548096.0000 - mae: 965450.3750 - val_loss: 962207088640.0000 - val_mae: 963705.3750
Epoch 35/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 959594233856.0000 - mae: 965350.3750 - val_loss: 962009038848.0000 - val_mae: 963602.8750
Epoch 36/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 959388975104.0000 - mae: 965244.6875 - val_loss: 961798340608.0000 - val_mae: 963494.0000
Epoch 37/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 959171067904.0000 - mae: 965131.8125 - val_loss: 961575649280.0000 - val_mae: 963378.8750
Epoch 38/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 958939856896.0000 - mae: 965012.5000 - val_loss: 961340964864.0000 - val_mae: 963257.6250
Epoch 39/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 958697701376.0000 - mae: 964887.1875 - val_loss: 961092911104.0000 - val_mae: 963129.3125
Epoch 40/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 958442176512.0000 - mae: 964754.6875 - val_loss: 960831553536.0000 - val_mae: 962994.1250
Epoch 41/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 958172364800.0000 - mae: 964615.6250 - val_loss: 960557350912.0000 - val_mae: 962852.3125
Epoch 42/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 957888724992.0000 - mae: 964469.3750 - val_loss: 960270303232.0000 - val_mae: 962703.8125
Epoch 43/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 957591715840.0000 - mae: 964316.1250 - val_loss: 959969558528.0000 - val_mae: 962548.1875
Epoch 44/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 957282582528.0000 - mae: 964155.6250 - val_loss: 959652757504.0000 - val_mae: 962384.3125
Epoch 45/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 956956475392.0000 - mae: 963987.3125 - val_loss: 959322652672.0000 - val_mae: 962213.3750
Epoch 46/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 956616933376.0000 - mae: 963811.3750 - val_loss: 958977474560.0000 - val_mae: 962034.6875
Epoch 47/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 956262187008.0000 - mae: 963627.5000 - val_loss: 958617419776.0000 - val_mae: 961848.1875
Epoch 48/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 955889745920.0000 - mae: 963435.8750 - val_loss: 958244126720.0000 - val_mae: 961654.8125
Epoch 49/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 955506098176.0000 - mae: 963236.6250 - val_loss: 957853335552.0000 - val_mae: 961452.3750
Epoch 50/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 955103313920.0000 - mae: 963029.3125 - val_loss: 957447929856.0000 - val_mae: 961242.3750

In [48]:
test_loss, test_mae = model.evaluate(X_test, y_test)

print("Test MSE:", test_loss)
print("Test MAE:", test_mae)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 960606830592.0000 - mae: 965994.2500
Test MSE: 960606830592.0
Test MAE: 965994.25

Model test verisi üzerinde değerlendirildi.

MAE değeri modelin ortalama tahmin hatasını gösterir.

Eğer training hatası çok düşük ama test hatası yüksek olsaydı
bu **overfitting** anlamına gelebilirdi.

Bu modelde train ve test hataları birbirine yakınsa
model genelleme yapabiliyor demektir.

In [49]:
new_car = np.array([[2020, 60000, 1.6, 110, 4]])

# normalize et
new_car = (new_car - X.min().values) / (X.max().values - X.min().values)

prediction = model.predict(new_car)

print("Tahmini araç fiyatı:", prediction[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Tahmini araç fiyatı: 6.455527e+07

Model verilen araç özelliklerine göre tahmini bir fiyat üretmiştir.

Gerçek hayatta bu tahmin:
- marka
- donanım
- piyasa talebi
- kaza geçmişi

gibi faktörlerden de etkilenir.

## Araba Fiyatları Analizi

Model sonuçlarına göre bazı özellikler fiyat üzerinde daha etkili olabilir.

Örneğin:

• Motor hacmi arttıkça fiyat artabilir  
• Beygir gücü yüksek araçlar genellikle daha pahalıdır  
• Kilometre arttıkça fiyat düşme eğilimindedir  
• Araç yaşı arttıkça fiyat azalabilir

### Modelin Güçlü Olduğu Durumlar

Model özellikle:
- benzer veri dağılımındaki araçları
- ortalama özelliklere sahip araçları

daha iyi tahmin eder.

### Modelin Zorlandığı Durumlar

Model şu araçlarda zorlanabilir:

- çok nadir araçlar
- lüks marka araçlar
- ekstrem kilometre veya motor değerleri

## Yönetici Özeti

• Ortalama tahmin hatası: ~20.000 TL civarında olabilir  
• Model ikinci el araç fiyat tahmini için kullanılabilir  
• Daha fazla veri ve gerçek piyasa verileri ile performans artırılabilir  
• Ek özellikler (marka, yakıt türü, kaza geçmişi vb.) eklenirse model daha doğru tahmin yapabilir